Repository mash-up-kr/moit-web, pull requests merged in 2023-08, with the labels that each got.

#59 feat: 룰 설정 스텝에서 시간 설정 UI 연결
  src/domain/moit/components/MinuteScreen.tsx
  src/screens/MoitRegisterScreen/steps/RuleSettingStep.tsx
Labels: ✨ feat

#66 refactor: 중복 로직 제거 및 컴포넌트 추상화
  src/constants/atomKeys.ts
  src/domain/moit/components/DateSelectScreen.tsx
  src/domain/moit/components/MinuteScreen.tsx
  src/domain/moit/components/TimeSelectBottomSheet.tsx
  src/domain/moit/constants/data.ts
  src/domain/moit/constants/index.ts
  src/screens/MoitRegisterScreen/atoms.ts
  src/screens/MoitRegisterScreen/components/DateSelectScreen.tsx
  src/screens/MoitRegisterScreen/components/DateZone.tsx
  src/screens/MoitRegisterScreen/components/MinuteScreen.tsx
  src/screens/MoitRegisterScreen/components/RepeatScreen.tsx
  src/screens/MoitRegisterScreen/components/SelectBottomSheet.tsx
  src/screens/MoitRegisterScreen/components/TimeSelectScreen.tsx
  src/screens/MoitRegisterScreen/components/TimeZone.tsx
  src/screens/MoitRegisterScreen/consts.ts
  src/screens/MoitRegisterScreen/hooks/useSelectBottomsheet.ts
  src/screens/MoitRegisterScreen/hooks/useSelectDate.ts
  src/screens/MoitRegisterScreen/hooks/useSelectTime.ts
  src/screens/MoitRegisterScreen/steps/RuleSettingStep.tsx
  src/screens/MoitRegisterScreen/steps/ScheduleSettingStep.tsx
  src/screens/MoitRegisterScreen/styled.ts
Labels: 🐈 원진, 🛠 refactor

#61 feat: MOIT 생성 유효성 검사 추가 & 정합성 개선
  .pnp.cjs
  .yarn/cache/dayjs-npm-1.11.9-c47d327b7c-a4844d83dc.zip
  README.md
  package.json
  src/components/Button.tsx
  src/constants/atomKeys.ts
  src/domain/moit/components/DateSelectScreen.tsx
  src/domain/moit/components/MinuteScreen.tsx
  src/domain/moit/components/RepeatScreen.tsx
  src/domain/moit/components/TimeSelectBottomSheet.tsx
  src/screens/MoitRegisterScreen/atoms.ts
  src/screens/MoitRegisterScreen/components/DateSelectScreen.tsx
  src/screens/MoitRegisterScreen/components/DateZone.tsx
  src/screens/MoitRegisterScreen/components/MinuteScreen.tsx
  src/screens/MoitRegisterScreen/components/RepeatScreen.tsx
  src/screens/MoitRegisterScreen/components/SelectBottomSheet.tsx
  src/screens/MoitRegisterScreen/components/TimeSelectScreen.tsx
  src/screens/MoitRegisterScreen/components/TimeZone.tsx
  src/screens/MoitRegisterScreen/consts.ts
  src/screens/MoitRegisterScreen/hooks/useSelectBottomsheet.ts
  src/screens/MoitRegisterScreen/hooks/useSelectDate.ts
  src/screens/MoitRegisterScreen/hooks/useSelectTime.ts
  src/screens/MoitRegisterScreen/steps/RuleSettingStep.tsx
  src/screens/MoitRegisterScreen/steps/ScheduleSettingStep.tsx
  src/screens/MoitRegisterScreen/styled.ts
  yarn.lock
Labels: ✨ feat, 🐈 원진
