Repository mash-up-kr/moit-web, pull requests merged in 2023-05, with the labels that each got.

#2 기본 Github Action 설정
  .github/CODEOWNERS
  .github/pr-labeler.config.yml
  .github/workflows/build-test-on-every-push.yml
  .github/workflows/pr-label.yml
Labels: ✨ feat, 🐈 원진

#3 fix: 액션 라벨 추가
  .github/pr-labeler.config.yml
Labels: 🐈 원진, 🐛 fix

#4 feat: eslint, prettier 설정 & README 초안 작성
  .eslintignore
  .eslintrc.cjs
  .prettierrc.json
  README.md
  package.json
  src/App.tsx
  src/assets/vite.svg
  src/main.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ✨ feat

#7 feat: CI 추가 설정
  .eslintrc.cjs
  .github/workflows/auto-assign.yml
  .husky/pre-commit
  .pnp.cjs
  .yarn/cache/ansi-escapes-npm-4.3.2-3ad173702f-93111c4218.zip
  .yarn/cache/ansi-regex-npm-6.0.1-8d663a607d-1ff8b7667c.zip
  .yarn/cache/ansi-styles-npm-6.2.1-d43647018c-ef940f2f0c.zip
  .yarn/cache/astral-regex-npm-2.0.0-f30d866aab-876231688c.zip
  .yarn/cache/chalk-npm-5.2.0-bedd808592-03d8060277.zip
  .yarn/cache/cli-cursor-npm-3.1.0-fee1e46b5e-2692784c6c.zip
  .yarn/cache/cli-truncate-npm-2.1.0-72184d3467-bf1e4e6195.zip
  .yarn/cache/cli-truncate-npm-3.1.0-654d2989ef-c3243e4197.zip
  .yarn/cache/colorette-npm-2.0.20-692d428726-0c016fea2b.zip
  .yarn/cache/commander-npm-10.0.1-f17613b72b-436901d64a.zip
  .yarn/cache/eastasianwidth-npm-0.2.0-c37eb16bd1-7d00d7cd8e.zip
  .yarn/cache/emoji-regex-npm-9.2.2-e6fac8d058-8487182da7.zip
  .yarn/cache/husky-npm-8.0.3-b0b59c5127-837bc7e441.zip
  .yarn/cache/is-fullwidth-code-point-npm-4.0.0-848488b60d-8ae89bf505.zip
  .yarn/cache/lilconfig-npm-2.1.0-a179261924-8549bb352b.zip
  .yarn/cache/lint-staged-npm-13.2.2-e66c493ac4-f34f6e2e85.zip
  .yarn/cache/listr2-npm-5.0.8-0d5e5a061b-8be9f56326.zip
  .yarn/cache/log-update-npm-4.0.0-9d0554261c-ae2f85bbab.zip
  .yarn/cache/normalize-path-npm-3.0.0-658ba7d77f-88eeb4da89.zip
  .yarn/cache/pidtree-npm-0.6.0-3d92e16117-8fbc073ede.zip
  .yarn/cache/restore-cursor-npm-3.1.0-52c5a4c98f-f877dd8741.zip
  .yarn/cache/rfdc-npm-1.3.0-272f288ad8-fb2ba8512e.zip
  .yarn/cache/rxjs-npm-7.8.1-41c443a75b-de4b53db10.zip
  .yarn/cache/slice-ansi-npm-3.0.0-d9999864af-5ec6d022d1.zip
  .yarn/cache/slice-ansi-npm-4.0.0-6eeca1d10e-4a82d7f085.zip
  .yarn/cache/slice-ansi-npm-5.0.0-8cd4f226df-7e600a2a55.zip
  .yarn/cache/string-argv-npm-0.3.2-6e057a88f1-8703ad3f3d.zip
  .yarn/cache/string-width-npm-5.1.2-bf60531341-7369deaa29.zip
  .yarn/cache/strip-ansi-npm-7.0.1-668c121204-257f78fa43.zip
  .yarn/cache/through-npm-2.3.8-df5f72a16e-a38c3e0598.zip
  .yarn/cache/tslib-npm-2.5.1-71910bf222-535e41e956.zip
  .yarn/cache/type-fest-npm-0.21.3-5ff2a9c6fd-e6b32a3b38.zip
  .yarn/cache/wrap-ansi-npm-6.2.0-439a7246d8-6cd96a4101.zip
  .yarn/cache/wrap-ansi-npm-7.0.0-ad6e1a0554-a790b846fd.zip
  .yarn/cache/yaml-npm-2.2.2-6e3cddb343-d90c235e09.zip
  package.json
  yarn.lock
Labels: ✨ feat, 🐈 원진
