Repository mash-up-kr/moit-web, pull requests merged in 2023-07, with the labels that each got.

#35 feat: API 레이어 구현
  .pnp.cjs
  .yarn/cache/axios-npm-1.4.0-4d7ce8ca3e-7fb6a4313b.zip
  .yarn/cache/follow-redirects-npm-1.15.2-1ec1dd82be-faa66059b6.zip
  .yarn/cache/form-data-npm-4.0.0-916facec2d-01135bf867.zip
  .yarn/sdks/prettier/index.js
  package.json
  src/App.tsx
  src/Example.tsx
  src/api/http.ts
  src/api/study/checkIsFirst.ts
  src/constants/queryKey.ts
  src/domain/study/hooks/useGetCheckIsFirst.ts
  vite.config.ts
  yarn.lock
Labels: ✨ feat, 🐈 원진

#33 feat: MO IT 생성 시간 바텀 시트 Pt2
  .pnp.cjs
  .yarn/cache/axios-npm-1.4.0-4d7ce8ca3e-7fb6a4313b.zip
  .yarn/cache/follow-redirects-npm-1.15.2-1ec1dd82be-faa66059b6.zip
  .yarn/cache/form-data-npm-4.0.0-916facec2d-01135bf867.zip
  .yarn/sdks/prettier/index.js
  package.json
  src/App.tsx
  src/Example.tsx
  src/api/http.ts
  src/api/study/checkIsFirst.ts
  src/components/BottomSheet.tsx
  src/components/SelectScroller/SelectScroller.hooks.ts
  src/components/SelectScroller/SelectScroller.tsx
  src/constants/queryKey.ts
  src/domain/moit/TimeSelectBottomSheet.tsx
  src/domain/moit/components/TimeZone.tsx
  src/domain/study/hooks/useGetCheckIsFirst.ts
  src/hooks/useEffectOnce.ts
  src/styles/globalStyle.ts
  src/styles/theme.ts
  vite.config.ts
  yarn.lock
Labels: ✨ feat, 🐈 원진

#36 feat: 스터디 등록화면 기본 스텝 구현
  .pnp.cjs
  .storybook/decorators.tsx
  .yarn/cache/react-hook-form-npm-7.45.1-9eaaa3061a-3abe1dcf44.zip
  package.json
  src/components/Button.tsx
  src/components/button.css
  src/screens/StudyRegisterScreen.tsx
  src/screens/StudyRegisterScreen/StudyRegisterScreen.tsx
  src/screens/StudyRegisterScreen/atoms.ts
  src/screens/StudyRegisterScreen/component/LargeBottom.tsx
  src/screens/StudyRegisterScreen/consts.ts
  src/screens/StudyRegisterScreen/index.tsx
  src/screens/StudyRegisterScreen/steps/InfoSettingStep.tsx
  src/screens/StudyRegisterScreen/steps/NotiSettingStep.tsx
  src/screens/StudyRegisterScreen/steps/RuleSettingStep.tsx
  src/screens/StudyRegisterScreen/steps/ScheduleSettingStep.tsx
  src/screens/StudyRegisterScreen/steps/index.ts
  src/stories/Button.stories.ts
  src/stories/StudyRegisterScreen.stories.tsx
  src/styles/theme.ts
  types/register.d.ts
  yarn.lock
Labels: ✨ feat, 🐶 영권

#49 🐛 fix: vercel.json 추가, 배포환경 라우팅 문제 처리
  vercel.json
Labels: 🐶 영권, 🐛 fix

#56 🐛 fix: input 포커스 시에 바텀시트 줌 현상 방지
  index.html
  src/screens/MoitRegisterScreen/MoitRegisterScreen.tsx
  src/screens/MoitRegisterScreen/steps/ScheduleSettingStep.tsx
Labels: 🐈 원진, 🐛 fix

#57 feat: 모잇 등록 완료화면 & api 연동
  src/api/moit/registerMoit.ts
  src/assets/png/trophy.png
  src/assets/svgs/PlusFill.svg
  src/bridge.ts
  src/components/SvgIcon.tsx
  src/constants/queryKey.ts
  src/domain/moit/components/DateSelectScreen.tsx
  src/hooks/MoitQuery.ts
  src/screens/MoitCompleteScreen/MoitCompleteScreen.tsx
  src/screens/MoitRegisterScreen/MoitRegisterScreen.tsx
  src/screens/MoitRegisterScreen/atoms.ts
  src/screens/MoitRegisterScreen/components/ButtonSelect.tsx
  src/screens/MoitRegisterScreen/components/ImageUploader.tsx
  src/screens/MoitRegisterScreen/components/LargeBottom.tsx
  src/screens/MoitRegisterScreen/consts.ts
  src/screens/MoitRegisterScreen/steps/InfoSettingStep.tsx
  src/screens/MoitRegisterScreen/steps/ScheduleSettingStep.tsx
  src/styles/icons.ts
  src/styles/pngs.ts
  src/utils/dateParser.ts
  types/moit.d.ts
Labels: ✨ feat

#60 출석 api 연동
  src/api/study/getStudyDetail.ts
  src/api/study/registerStudyKeyword.ts
  src/bridge.ts
  src/constants/queryKey.ts
  src/hooks/AttendanceQuery.ts
  src/screens/AttendanceScreen/AttendanceKeywordScreen.tsx
  src/screens/AttendanceScreen/AttendanceResultScreen.tsx
  src/screens/AttendanceScreen/components/AttendanceList.tsx
  src/screens/AttendanceScreen/components/AttendanceTimer.tsx
  src/screens/AttendanceScreen/components/LiveStatusCard.tsx
  types/study.d.ts
Labels: ✨ feat
