Repository mash-up-kr/moit-web, pull requests merged in 2023-06, with the labels that each got.

#17 feat: Emotion Theme 적용
  .eslintrc.cjs
  src/Example.tsx
  src/main.tsx
  src/styles/theme.ts
  types/emotion.d.ts
Labels: ✨ feat, 🦦 영지

#13 feat: Bottom Sheet 구현
  index.html
  src/components/BaseModal.tsx
  src/components/BottomSheet.tsx
  src/hooks/useModal.ts
  src/hooks/useScrollLock.ts
  src/styles/keyframes.ts
  src/styles/z-index.ts
Labels: ✨ feat, 🐈 원진

#21 feat: Storybook 애드온 추가
  .pnp.cjs
  .storybook/main.ts
  .storybook/preview.ts
  .yarn/cache/@storybook-addon-a11y-npm-7.0.22-acfc22d168-09004f336b.zip
  .yarn/cache/@storybook-addon-highlight-npm-7.0.22-594d538c63-4dc8bf03ba.zip
  .yarn/cache/@storybook-addon-viewport-npm-7.0.22-b30c0d6da5-b73cbf6eb5.zip
  .yarn/cache/@storybook-channel-postmessage-npm-7.0.22-8a3143f81d-cbca15c9ab.zip
  .yarn/cache/@storybook-channels-npm-7.0.22-4645122cca-6da7acedce.zip
  .yarn/cache/@storybook-client-logger-npm-7.0.22-174d8c8dd2-3d115b65f3.zip
  .yarn/cache/@storybook-components-npm-7.0.22-6be464fbcc-92b804d5da.zip
  .yarn/cache/@storybook-core-events-npm-7.0.22-f5e62a4cef-684daca6bd.zip
  .yarn/cache/@storybook-manager-api-npm-7.0.22-d8b5650685-ec0657c6be.zip
  .yarn/cache/@storybook-preview-api-npm-7.0.22-c821410a0e-d4af5770d1.zip
  .yarn/cache/@storybook-router-npm-7.0.22-1b5ddaecaf-4cd7dee055.zip
  .yarn/cache/@storybook-theming-npm-7.0.22-164b6ba5ec-061642c487.zip
  .yarn/cache/@storybook-types-npm-7.0.22-ca008c3abd-33a6279bde.zip
  .yarn/cache/axe-core-npm-4.7.2-678c3cf6c4-5d86fa0f45.zip
  .yarn/cache/react-resize-detector-npm-7.1.2-146e0b9a4f-55f4abad7f.zip
  package.json
  yarn.lock
Labels: ✨ feat, 🐶 영권

#27 feat: 폰트 적용 및 Text Component 생성
  src/Example.tsx
  src/components/Text.tsx
  src/main.tsx
  src/styles/fonts/Pretendard-Bold.woff
  src/styles/fonts/Pretendard-Medium.woff
  src/styles/fonts/Pretendard-Regular.woff
  src/styles/fonts/Pretendard-SemiBold.woff
  src/styles/globalStyle.ts
  src/styles/theme.ts
Labels: ✨ feat, 🦦 영지

#28 feat: ScreenHeader 컴포넌트에 스타일 추가
  .storybook/preview.ts
  src/components/ScreenHeader.tsx
  src/stories/ScreenHeader.stories.tsx
Labels: ✨ feat, 🐶 영권

#31 fix: ChakraTheme 설정
  .storybook/decorators.tsx
  .storybook/preview.ts
  src/components/ScreenHeader.tsx
  src/components/SvgIcon.tsx
  src/main.tsx
  src/screens/StudyRegisterScreen.tsx
  src/styles/theme.ts
Labels: 🐶 영권, 🐛 fix

#22 feat: 스크롤 셀렉트 컴포넌트 구현 (MOIT 생성 시간 선택 바텀시트 구현)
  src/Example.tsx
  src/components/BottomSheet.tsx
  src/components/SelectScroller/SelectScroller.hooks.ts
  src/components/SelectScroller/SelectScroller.option.tsx
  src/components/SelectScroller/SelectScroller.tsx
  src/components/SelectScroller/index.ts
  src/domain/moit/TimeSelectBottomSheet.tsx
  src/domain/moit/components/TimeZone.tsx
  src/domain/moit/hooks/useSelectTime.ts
  src/styles/theme.ts
  src/styles/z-index.ts
  src/utils/generateArray.ts
  types/moit.d.ts
Labels: ✨ feat, 🐈 원진
